services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./app:/app/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_MAX_FILE_SIZE: ${NEXT_PUBLIC_MAX_FILE_SIZE}
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
