FROM node:20-alpine



WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

ARG BASE_URL
ARG SERVER_HOST
ARG DATABASE_URL
ARG SESSION_SECRET
ARG REDIS_PASSWORD
ARG REDIS_PORT
ARG FILE_ENCRYPTION_KEY
ARG ADMIN_USERNAME
ARG ADMIN_EMAIL
ARG ADMIN_PASSWORD

ENV BASE_URL=${BASE_URL}
ENV SERVER_HOST=${SERVER_HOST}
ENV DATABASE_URL=${DATABASE_URL}
ENV SESSION_SECRET=${SESSION_SECRET}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_PORT=${REDIS_PORT}
ENV FILE_ENCRYPTION_KEY=${FILE_ENCRYPTION_KEY}
ENV ADMIN_USERNAME=${ADMIN_USERNAME}
ENV ADMIN_EMAIL=${ADMIN_EMAIL}
ENV ADMIN_PASSWORD=${ADMIN_PASSWORD}

RUN npx prisma generate
RUN npm run build

COPY docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

CMD ["/app/docker-entrypoint.sh"]
